# Michael Coleman
# August 5th
# Team Stats

from players import players, nba_teams, nba_team_search


team_stats = {

    "Thunder": {
        "points_per_game": 119.0,
        "opponent_points_per_game": 107.9,
        "offensive_rating": 117.6,
        "defensive_rating": 106.5,
        "pace": 100.37,
        "wins": 64,
        "losses": 18,
        "fg_pct": 48.4,
        "three_pct": 36.5,
        "offensive_rebounds_per_game": 9.6,
        "defensive_rebounds_per_game": 34.6,
        "rebounds_per_game": 44.1,
        "rebound_pct": 49.0,
        "assists_per_game": 25.8,
        "ast_to_ratio": 2.05,
        "turnovers_per_game": 12.6,
        "turnover_pct": 12.4,
        "steals_per_game": 9.7,
        "blocks_per_game": 5.5
    },

    "Spurs": {
        "points_per_game": 119.8,
        "opponent_points_per_game": 111.5,
        "offensive_rating": 118.7,
        "defensive_rating": 110.4,
        "pace": 100.72,
        "wins": 62,
        "losses": 20,
        "fg_pct": 48.3,
        "three_pct": 35.9,
        "offensive_rebounds_per_game": 11.4,
        "defensive_rebounds_per_game": 35.6,
        "rebounds_per_game": 47.0,
        "rebound_pct": 52.1,
        "assists_per_game": 28.1,
        "ast_to_ratio": 2.09,
        "turnovers_per_game": 13.5,
        "turnover_pct": 13.3,
        "steals_per_game": 7.5,
        "blocks_per_game": 5.5
    },

    "Pistons": {
        "points_per_game": 117.8,
        "opponent_points_per_game": 109.6,
        "offensive_rating": 117.3,
        "defensive_rating": 108.9,
        "pace": 99.88,
        "wins": 60,
        "losses": 22,
        "fg_pct": 48.5,
        "three_pct": 35.6,
        "offensive_rebounds_per_game": 13.1,
        "defensive_rebounds_per_game": 32.5,
        "rebounds_per_game": 45.6,
        "rebound_pct": 52.4,
        "assists_per_game": 27.8,
        "ast_to_ratio": 1.84,
        "turnovers": 15.1,
        "turnover_pct": 15.1,
        "steals_per_game": 10.4,
        "blocks_per_game": 6.4
    },

    "Celtics": {
        "points_per_game": 114.9,
        "opponent_points_per_game": 107.2,
        "offensive_rating": 120.0,
        "defensive_rating": 111.7,
        "pace": 95.58,
        "wins": 56,
        "losses": 26,
        "fg_pct": 46.7,
        "three_pct": 36.7,
        "offensive_rebounds_per_game": 12.5,
        "defensive_rebounds_per_game": 33.9,
        "rebounds_per_game": 46.4,
        "rebound_pct": 52.5,
        "assists_per_game": 24.6,
        "ast_to_ratio": 1.99,
        "turnovers_per_game": 12.4,
        "turnover_pct": 12.9,
        "steals_per_game": 7.1,
        "blocks_per_game": 5.0
    },

    "Nuggets": {
        "points_per_game": 122.1,
        "opponent_points_per_game": 117.0,
        "offensive_rating": 121.2,
        "defensive_rating": 116.0,
        "pace": 99.49,
        "wins": 54,
        "losses": 28,
        "fg_pct": 49.6,
        "three_pct": 39.6,
        "offensive_rebounds_per_game": 9.8,
        "defensive_rebounds_per_game": 34.2,
        "rebounds_per_game": 44.0,
        "rebound_pct": 51.1,
        "assists_per_game": 29.0,
        "ast_to_ratio": 2.25,
        "turnovers_per_game": 12.9,
        "turnover_pct": 12.8,
        "steals_per_game": 6.8,
        "blocks_per_game": 4.0
    },

    "Lakers": {
        "points_per_game": 116.3,
        "opponent_points_per_game": 114.5,
        "offensive_rating": 117.0,
        "defensive_rating": 115.5,
        "pace": 99.22,
        "wins": 53,
        "losses": 29,
        "fg_pct": 50.2,
        "three_pct": 35.9,
        "offensive_rebounds_per_game": 9.4,
        "defensive_rebounds_per_game": 31.5,
        "rebounds_per_game": 41.0,
        "rebound_pct": 49.9,
        "assists_per_game": 25.9,
        "ast_to_ratio": 1.79,
        "turnovers_per_game": 14.5,
        "turnover_pct": 14.6,
        "steals_per_game": 8.5,
        "blocks_per_game": 4.3
    },

    "Knicks": {
        "points_per_game": 116.5,
        "opponent_points_per_game": 110.2,
        "offensive_rating": 118.7,
        "defensive_rating": 112.3,
        "pace": 97.71,
        "wins": 53,
        "losses": 29,
        "fg_pct": 47.8,
        "three_pct": 37.3,
        "offensive_rebounds_per_game": 12.7,
        "defensive_rebounds_per_game": 32.9,
        "rebounds_per_game": 45.6,
        "rebound_pct": 52.2,
        "assists_per_game": 27.4,
        "ast_to_ratio": 2.01,
        "turnovers_per_game": 13.6,
        "turnover_pct": 13.9,
        "steals_per_game": 8.1,
        "blocks_per_game": 3.9
    },

    "Cavaliers": {
        "points_per_game": 119.5,
        "opponent_points_per_game": 115.4,
        "offensive_rating": 118.3,
        "defensive_rating": 114.1,
        "pace": 100.70,
        "wins": 52,
        "losses": 30,
        "fg_pct": 48.2,
        "three_pct": 36.0,
        "offensive_rebounds_per_game": 11.7,
        "defensive_rebounds_per_game": 32.7,
        "rebounds_per_game": 44.4,
        "rebound_pct": 50.2,
        "assists_per_game": 28.3,
        "ast_to_ratio": 2.02,
        "turnovers_per_game": 14.0,
        "turnover_pct": 13.8,
        "steals_per_game": 8.5,
        "blocks_per_game": 5.0
    },

    "Rockets": {
        "points_per_game": 115.2,
        "opponent_points_per_game": 110.0,
        "offensive_rating": 117.5,
        "defensive_rating": 112.1,
        "pace": 96.98,
        "wins": 52,
        "losses": 30,
        "fg_pct": 47.9,
        "three_pct": 36.4,
        "offensive_rebounds_per_game": 15.0,
        "defensive_rebounds_per_game": 33.1,
        "rebounds_per_game": 48.1,
        "rebound_pct": 54.5,
        "assists_per_game": 25.4,
        "ast_to_ratio": 1.65,
        "turnovers_per_game": 15.4,
        "turnover_pct": 15.7,
        "steals_per_game": 8.5,
        "blocks_per_game": 5.8
    },

    "Timberwolves": {
        "points_per_game": 118.0,
        "opponent_points_per_game": 114.6,
        "offensive_rating": 115.6,
        "defensive_rating": 112.5,
        "pace": 101.50,
        "wins": 49,
        "losses": 33,
        "fg_pct": 48.1,
        "three_pct": 37.0,
        "offensive_rebounds_per_game": 11.1,
        "defensive_rebounds_per_game": 33.0,
        "rebounds_per_game": 44.1,
        "rebound_pct": 49.9,
        "assists_per_game": 26.1,
        "ast_to_ratio": 1.76,
        "turnovers_per_game": 14.8,
        "turnover_pct": 14.5,
        "steals_per_game": 8.7,
        "blocks_per_game": 5.8
    },

    "Hawks": {
        "points_per_game": 118.5,
        "opponent_points_per_game": 116.1,
        "offensive_rating": 115.0,
        "defensive_rating": 112.9,
        "pace": 102.50,
        "wins": 46,
        "losses": 36,
        "fg_pct": 47.4,
        "three_pct": 37.1,
        "offensive_rebounds_per_game": 11.0,
        "defensive_rebounds_per_game": 32.6,
        "rebounds_per_game": 43.5,
        "rebound_pct": 49.5,
        "assists_per_game": 30.1,
        "ast_to_ratio": 2.13,
        "turnovers_per_game": 14.2,
        "turnover_pct": 13.8,
        "steals_per_game": 9.4,
        "blocks_per_game": 4.7
    },

    "Raptors": {
        "points_per_game": 114.6,
        "opponent_points_per_game": 111.8,
        "offensive_rating": 115.0,
        "defensive_rating": 112.1,
        "pace": 99.22,
        "wins": 46,
        "losses": 36,
        "fg_pct": 48.2,
        "three_pct": 35.4,
        "offensive_rebounds_per_game": 10.9,
        "defensive_rebounds_per_game": 31.2,
        "rebounds_per_game": 42.1,
        "rebound_pct": 49.6,
        "assists_per_game": 29.5,
        "ast_to_ratio": 2.16,
        "turnovers_per_game": 13.7,
        "turnover_pct": 13.7,
        "steals_per_game": 8.8,
        "blocks_per_game": 4.8
    },

    "Magic": {
        "points_per_game": 115.7,
        "opponent_points_per_game": 115.1,
        "offensive_rating": 114.2,
        "defensive_rating": 113.6,
        "pace": 100.56,
        "wins": 45,
        "losses": 37,
        "fg_pct": 46.4,
        "three_pct": 34.3,
        "offensive_rebounds_per_game": 11.0,
        "defensive_rebounds_per_game": 32.4,
        "rebounds_per_game": 43.4,
        "rebound_pct": 50.5,
        "assists_per_game": 26.5,
        "ast_to_ratio": 1.87,
        "turnovers_per_game": 14.2,
        "turnover_pct": 14.0,
        "steals_per_game": 8.5,
        "blocks_per_game": 4.7
    },

    "Sixers": {
        "points_per_game": 115.9,
        "opponent_points_per_game": 116.1,
        "offensive_rating": 114.3,
        "defensive_rating": 114.4,
        "pace": 100.39,
        "wins": 45,
        "losses": 37,
        "fg_pct": 46.2,
        "three_pct": 34.9,
        "offensive_rebounds_per_game": 11.8,
        "defensive_rebounds_per_game": 31.8,
        "rebounds_per_game": 43.6,
        "rebound_pct": 49.1,
        "assists_per_game": 24.6,
        "ast_to_ratio": 1.81,
        "turnovers_per_game": 13.6,
        "turnover_pct": 13.4,
        "steals_per_game": 9.1,
        "blocks_per_game": 5.7
    },

    "Suns": {
        "points_per_game": 112.6,
        "opponent_points_per_game": 111.1,
        "offensive_rating": 114.2,
        "defensive_rating": 112.9,
        "pace": 98.14,
        "wins": 45,
        "losses": 37,
        "fg_pct": 45.5,
        "three_pct": 36.1,
        "offensive_rebounds_per_game": 13.0,
        "defensive_rebounds_per_game": 30.1,
        "rebounds_per_game": 43.1,
        "rebound_pct": 49.8,
        "assists_per_game": 24.6,
        "ast_to_ratio": 1.70,
        "turnovers_per_game": 14.5,
        "turnover_pct": 14.7,
        "steals_per_game": 9.5,
        "blocks_per_game": 4.2
    },

    "Hornets": {
        "points_per_game": 116.0,
        "opponent_points_per_game": 111.2,
        "offensive_rating": 118.4,
        "defensive_rating": 113.5,
        "pace": 97.59,
        "wins": 44,
        "losses": 38,
        "fg_pct": 46.0,
        "three_pct": 37.8,
        "offensive_rebounds_per_game": 12.8,
        "defensive_rebounds_per_game": 33.3,
        "rebounds_per_game": 46.1,
        "rebound_pct": 53.9,
        "assists_per_game": 26.3,
        "ast_to_ratio": 1.71,
        "turnovers_per_game": 15.4,
        "turnover_pct": 15.7,
        "steals_per_game": 7.0,
        "blocks_per_game": 4.5
    },

    "Heat": {
        "points_per_game": 120.9,
        "opponent_points_per_game": 118.6,
        "offensive_rating": 115.8,
        "defensive_rating": 113.6,
        "pace": 104.22,
        "wins": 43,
        "losses": 39,
        "fg_pct": 46.8,
        "three_pct": 36.1,
        "offensive_rebounds_per_game": 11.8,
        "defensive_rebounds_per_game": 34.5,
        "rebounds_per_game": 46.3,
        "rebound_pct": 49.9,
        "assists_per_game": 29.0,
        "ast_to_ratio": 2.12,
        "turnovers_per_game": 13.7,
        "turnover_pct": 13.1,
        "steals_per_game": 8.6,
        "blocks_per_game": 4.3
    },

    "Clippers": {
        "points_per_game": 113.8,
        "opponent_points_per_game": 112.7,
        "offensive_rating": 116.3,
        "defensive_rating": 115.2,
        "pace": 97.29,
        "wins": 42,
        "losses": 40,
        "fg_pct": 48.4,
        "three_pct": 36.8,
        "offensive_rebounds_per_game": 9.6,
        "defensive_rebounds_per_game": 31.0,
        "rebounds_per_game": 40.6,
        "rebound_pct": 49.0,
        "assists_per_game": 23.7,
        "ast_to_ratio": 1.66,
        "turnovers_per_game": 14.3,
        "turnover_pct": 14.7,
        "steals_per_game": 9.0,
        "blocks_per_game": 4.9
    },

    "Trail Blazers": {
        "points_per_game": 115.5,
        "opponent_points_per_game": 115.8,
        "offensive_rating": 113.1,
        "defensive_rating": 113.5,
        "pace": 101.63,
        "wins": 42,
        "losses": 40,
        "fg_pct": 45.3,
        "three_pct": 34.3,
        "offensive_rebounds_per_game": 14.1,
        "defensive_rebounds_per_game": 31.9,
        "rebounds_per_game": 46.0,
        "rebound_pct": 51.7,
        "assists_per_game": 25.1,
        "ast_to_ratio": 1.46,
        "turnovers_per_game": 17.3,
        "turnover_pct": 16.9,
        "steals_per_game": 8.3,
        "blocks_per_game": 5.5
    },

    "Warriors": {
        "points_per_game": 114.6,
        "opponent_points_per_game": 115.2,
        "offensive_rating": 113.8,
        "defensive_rating": 114.4,
        "pace": 100.05,
        "wins": 37,
        "losses": 45,
        "fg_pct": 46.1,
        "three_pct": 35.6,
        "offensive_rebounds_per_game": 11.4,
        "defensive_rebounds_per_game": 31.0,
        "rebounds_per_game": 42.3,
        "rebound_pct": 49.0,
        "assists_per_game": 28.9,
        "ast_to_ratio": 1.85,
        "turnovers_per_game": 15.7,
        "turnover_pct": 15.6,
        "steals_per_game": 9.7,
        "blocks_per_game": 4.2
    },

    "Bucks": {
        "points_per_game": 110.6,
        "opponent_points_per_game": 116.8,
        "offensive_rating": 112.2,
        "defensive_rating": 118.3,
        "pace": 98.33,
        "wins": 32,
        "losses": 50,
        "fg_pct": 47.7,
        "three_pct": 38.7,
        "offensive_rebounds_per_game": 8.9,
        "defensive_rebounds_per_game": 31.8,
        "rebounds_per_game": 40.7,
        "rebound_pct": 48.2,
        "assists_per_game": 25.8,
        "ast_to_ratio": 1.70,
        "turnovers_per_game": 15.2,
        "turnover_pct": 15.4,
        "steals_per_game": 7.4,
        "blocks_per_game": 4.0
    },

    "Bulls": {
        "points_per_game": 116.3,
        "opponent_points_per_game": 121.5,
        "offensive_rating": 112.1,
        "defensive_rating": 117.4,
        "pace": 103.22,
        "wins": 31,
        "losses": 51,
        "fg_pct": 46.9,
        "three_pct": 35.6,
        "offensive_rebounds_per_game": 10.4,
        "defensive_rebounds_per_game": 34.7,
        "rebounds_per_game": 45.0,
        "rebound_pct": 49.6,
        "assists_per_game": 28.5,
        "ast_to_ratio": 1.86,
        "turnovers_per_game": 15.3,
        "turnover_pct": 14.8,
        "steals_per_game": 7.6,
        "blocks_per_game": 5.0
    },

    "Mavericks": {
        "points_per_game": 114.1,
        "opponent_points_per_game": 119.6,
        "offensive_rating": 110.3,
        "defensive_rating": 115.5,
        "pace": 102.62,
        "wins": 26,
        "losses": 56,
        "fg_pct": 46.0,
        "three_pct": 34.4,
        "offensive_rebounds_per_game": 10.5,
        "defensive_rebounds_per_game": 34.2,
        "rebounds_per_game": 44.7,
        "rebound_pct": 49.2,
        "assists_per_game": 25.3,
        "ast_to_ratio": 1.74,
        "turnovers_per_game": 14.5,
        "turnover_pct": 14.1,
        "steals_per_game": 7.5,
        "blocks_per_game": 5.2
    },

    "Pelicans": {
        "points_per_game": 115.5,
        "opponent_points_per_game": 120.0,
        "offensive_rating": 113.3,
        "defensive_rating": 117.6,
        "pace": 101.37,
        "wins": 26,
        "losses": 56,
        "fg_pct": 46.6,
        "three_pct": 34.7,
        "offensive_rebounds_per_game": 12.2,
        "defensive_rebounds_per_game": 31.7,
        "rebounds_per_game": 43.9,
        "rebound_pct": 49.1,
        "assists_per_game": 25.1,
        "ast_to_ratio": 1.77,
        "turnovers_per_game": 14.2,
        "turnover_pct": 13.9,
        "steals_per_game": 8.9,
        "blocks_per_game": 5.2
    },

    "Grizzlies": {
        "points_per_game": 114.7,
        "opponent_points_per_game": 120.7,
        "offensive_rating": 112.4,
        "defensive_rating": 118.4,
        "pace": 101.69,
        "wins": 25,
        "losses": 57,
        "fg_pct": 45.6,
        "three_pct": 35.3,
        "offensive_rebounds_per_game": 11.2,
        "defensive_rebounds_per_game": 31.0,
        "rebounds_per_game": 42.1,
        "rebound_pct": 47.8,
        "assists_per_game": 27.8,
        "ast_to_ratio": 1.85,
        "turnovers_per_game": 15.1,
        "turnover_pct": 14.8,
        "steals_per_game": 8.8,
        "blocks_per_game": 4.8
    },

    "Kings": {
        "points_per_game": 111.0,
        "opponent_points_per_game": 121.0,
        "offensive_rating": 110.6,
        "defensive_rating": 120.3,
        "pace": 100.12,
        "wins": 22,
        "losses": 60,
        "fg_pct": 46.7,
        "three_pct": 34.0,
        "offensive_rebounds_per_game": 11.5,
        "defensive_rebounds_per_game": 30.8,
        "rebounds_per_game": 42.3,
        "rebound_pct": 48.7,
        "assists_per_game": 25.5,
        "ast_to_ratio": 1.78,
        "turnovers_per_game": 14.3,
        "turnover_pct": 14.3,
        "steals_per_game": 8.0,
        "blocks_per_game": 4.5
    },

    "Jazz": {
        "points_per_game": 117.6,
        "opponent_points_per_game": 126.0,
        "offensive_rating": 112.7,
        "defensive_rating": 120.8,
        "pace": 103.54,
        "wins": 22,
        "losses": 60,
        "fg_pct": 46.7,
        "three_pct": 34.5,
        "offensive_rebounds_per_game": 12.0,
        "defensive_rebounds_per_game": 31.8,
        "rebounds_per_game": 43.8,
        "rebound_pct": 49.2,
        "assists_per_game": 29.6,
        "ast_to_ratio": 1.91,
        "turnovers_per_game": 15.5,
        "turnover_pct": 14.9,
        "steals_per_game": 8.9,
        "blocks_per_game": 3.8
    },

    "Nets": {
        "points_per_game": 105.9,
        "opponent_points_per_game": 115.9,
        "offensive_rating": 108.2,
        "defensive_rating": 118.2,
        "pace": 97.60,
        "wins": 20,
        "losses": 62,
        "fg_pct": 44.3,
        "three_pct": 34.0,
        "offensive_rebounds_per_game": 10.3,
        "defensive_rebounds_per_game": 29.0,
        "rebounds_per_game": 39.3,
        "rebound_pct": 47.8,
        "assists_per_game": 25.0,
        "ast_to_ratio": 1.59,
        "turnovers_per_game": 15.8,
        "turnover_pct": 16.1,
        "steals_per_game": 8.0,
        "blocks_per_game": 4.3
    },

    "Pacers": {
        "points_per_game": 112.4,
        "opponent_points_per_game": 120.4,
        "offensive_rating": 110.1,
        "defensive_rating": 117.9,
        "pace": 101.78,
        "wins": 19,
        "losses": 63,
        "fg_pct": 45.8,
        "three_pct": 35.6,
        "offensive_rebounds_per_game": 9.8,
        "defensive_rebounds_per_game": 32.1,
        "rebounds_per_game": 41.9,
        "rebound_pct": 47.5,
        "assists_per_game": 27.7,
        "ast_to_ratio": 1.91,
        "turnovers_per_game": 14.5,
        "turnover_pct": 14.2,
        "steals_per_game": 7.4,
        "blocks_per_game": 4.6
    },

    "Wizards": {
        "points_per_game": 112.9,
        "opponent_points_per_game": 124.9,
        "offensive_rating": 109.7,
        "defensive_rating": 121.5,
        "pace": 102.49,
        "wins": 17,
        "losses": 65,
        "fg_pct": 46.3,
        "three_pct": 35.9,
        "offensive_rebounds_per_game": 11.0,
        "defensive_rebounds_per_game": 30.9,
        "rebounds_per_game": 41.9,
        "rebound_pct": 47.1,
        "assists_per_game": 25.0,
        "ast_to_ratio": 1.60,
        "turnovers_per_game": 15.7,
        "turnover_pct": 15.2,
        "steals_per_game": 8.0,
        "blocks_per_game": 5.5
    }
}

team_stats_search = {
    "lakers": "Lakers",
    "los angeles lakers": "Lakers",
    "la lakers": "Lakers",

    "warriors": "Warriors",
    "golden state warriors": "Warriors",

    "clippers": "Clippers",
    "los angeles clippers": "Clippers",
    "la clippers": "Clippers",

    "nuggets": "Nuggets",
    "denver nuggets": "Nuggets",

    "pistons": "Pistons",
    "detroit pistons": "Pistons",

    "celtics": "Celtics",
    "boston celtics": "Celtics",

    "bucks": "Bucks",
    "milwaukee bucks": "Bucks",

    "heat": "Heat",
    "miami heat": "Heat",

    "suns": "Suns",
    "phoenix suns": "Suns",

    "jazz": "Jazz",
    "utah jazz": "Jazz",

    "mavericks": "Mavericks",
    "mavs": "Mavericks",
    "dallas mavericks": "Mavericks",

    "rockets": "Rockets",
    "houston rockets": "Rockets",

    "knicks": "Knicks",
    "new york knicks": "Knicks",

    "nets": "Nets",
    "brooklyn nets": "Nets",

    "bulls": "Bulls",
    "chicago bulls": "Bulls",

    "hornets": "Hornets",
    "charlotte hornets": "Hornets",

    "hawks": "Hawks",
    "atlanta hawks": "Hawks",

    "pacers": "Pacers",
    "indiana pacers": "Pacers",

    "magic": "Magic",
    "orlando magic": "Magic",

    "wizards": "Wizards",
    "washington wizards": "Wizards",

    "timberwolves": "Timberwolves",
    "wolves": "Timberwolves",
    "minnesota timberwolves": "Timberwolves",

    "pelicans": "Pelicans",
    "new orleans pelicans": "Pelicans",

    "trail blazers": "Trail Blazers",
    "trailblazers": "Trail Blazers",
    "blazers": "Trail Blazers",
    "portland trail blazers": "Trail Blazers",

    "kings": "Kings",
    "sacramento kings": "Kings",

    "spurs": "Spurs",
    "san antonio spurs": "Spurs",

    "thunder": "Thunder",
    "oklahoma city thunder": "Thunder",
    "okc thunder": "Thunder",

    "grizzlies": "Grizzlies",
    "memphis grizzlies": "Grizzlies",

    "raptors": "Raptors",
    "toronto raptors": "Raptors",

    "cavaliers": "Cavaliers",
    "cavs": "Cavaliers",
    "cleveland cavaliers": "Cavaliers",

    "76ers": "Sixers",
    "sixers": "Sixers",
    "philadelphia 76ers": "Sixers",
}